# nmake makefile
#
# Tools used:
#  Compile::Resource Compiler
#  Compile::GNU C
#  Make: nmake or GNU make
all: dlg.exe

dlg.exe : dlg.obj dlg.res dlg.def
	gcc -Zomf dlg.obj dlg.res dlg.def -o dlg.exe
	wrc dlg.res

dlg.obj : dlg.c
	gcc -Wall -Zomf -c -O2 dlg.c -o dlg.obj

dlg.res : dlg.rc
	wrc -r dlg.rc

clean :
	rm -rf *exe *RES *obj
